### PR TITLE
Added A2C models for Ant-v3, Humanoid-v3 and Walker2d-v3 environments

### PR DESCRIPTION
**Pull request by pseudo-rnd-thoughts**
The SB3 benchmarks are missing the A2C Ant, Humanoid and Walker2d environments, [benchmarks](https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/benchmark.md) and [zoo](https://github.com/DLR-RM/rl-baselines3-zoo)

This PR adds those environments for A2C

### CODE REVIEW

**Comment by araffin** [comment]
Hello,
thanks.
I think I will actually wait for Huggingface integration https://github.com/DLR-RM/rl-baselines3-zoo/pull/198 (same as https://github.com/DLR-RM/rl-baselines3-zoo/pull/244)

**Comment by pseudo-rnd-thoughts** [comment]
No worries

**Comment by araffin** [comment]
Basic version is ready to review ;)
https://github.com/DLR-RM/rl-baselines3-zoo/pull/250

An example: https://huggingface.co/sb3/ppo-MountainCarContinuous-v0

**Comment by pseudo-rnd-thoughts** [comment]
Sorry, I didn't totally understand what you want me to do

**Comment by araffin** [comment]
> Sorry, I didn't totally understand what you want me to do

sorry, we are going to replace the trained agents repo with huggingface hub, and the PR for that is ready, you can use it to upload models ;)

**Comment by araffin** [comment]
Closing in favor of https://github.com/DLR-RM/rl-baselines3-zoo/pull/262
models are now uploaded on Hugginface hub, see https://huggingface.co/sb3/a2c-Walker2d-v3 for instance.
Btw, the pre-trained models do not have good performance and are missing some hyperparameter tuning (as expected, that was the reason I didn't upload them in the first place).

**Pull request closed without merging**
